config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :super_users, controllers: { sessions: 'super_users/sessions' }
  devise_for :users, controllers: {sessions: 'users/sessions'}


  root 'pages#index'
  get 'profile' => 'dashboard#profile'
  get 'dashboard' => 'dashboard#index', as: :users_root

  # тянем картинку к пользователю по этому урлу
  get '/users/:user/images/:image_type' => 'users/images#show', :as => :user_image

  resources :units, only: [:index] do
    resources :bubbles, only: [:create, :destroy], :controller => 'unit_bubbles'
  end



  scope module: 'super_users' do
    scope '/superuser' do
      root 'dashboard#index', as: :super_user_root
      resources :organizations, except: [:show], as: :super_user_organizations
      resources :users, except: [:show], as: :super_user_users
      resources :roles, except: [:show], as: :super_user_roles
      resources :permissions, only: [:index], as: :super_user_permissions
      resources :logs,  only: [:index], as: :super_user_logs
      resources :units, only: [:index], as: :super_user_units do
        get 'upload', on: :collection
        post 'import', on: :collection
      end
    end
  end

  namespace 'control' do

    get 'dashboard' => 'dashboard#index'

    get 'clean' => 'dashboard#clean', as: :dashboard_clean
    # TODO: try to rewrite to be like "POST /dashboard/activate"
    get 'activate' => 'dashboard#activate'

    resources :regulations do
      get 'change_state', on: :collection
    end

  end

  get 'control/dashboard', to: 'control/dashboard#index'

  match 'under_construction' => 'errors#under_construction', via: :get
  match '/500' => 'errors#error_500', via: :get
  match '/404' => 'errors#error_404', via: :get

  namespace :api do
    resources :units, only: [:index] do
      collection do
        get :states
      end
    end
    resources :unit_bubbles, only: [:index] do
      collection do
         get 'nested_bubbles_amount'
      end
    end

    scope module: :im do
      resources :dialogues, only: [:index]
      resource :broadcast, only: [:show]
    end

    namespace :im do
      resources :organizations, only: [:show]
    end

    resources :notifications, only: [:index, :new]
  end

  scope module: :im do
    scope :messages do
      resource :broadcast, only: [:show, :create], as: :messages_broadcast do
        post 'clear_notifications'
      end

      # messages between organizations
      get 'organization/:id' => 'organizations#show', as: :messages_organization
      post 'organization/:id' => 'organizations#create', as: :messages_organizations
      post 'organization/:id/clear_notifications' => 'organizations#clear_notifications', as: :message_organizations_clear
    end
    resources :dialogues, only: [:index]
  end


  # Документооборот
  get '/documents' => 'documents/documents#index', as: :documents
  namespace :documents do
    resources :documents, path:'', only: [:index, :edit, :show, :update, :destroy] do
      post 'search', on: :collection
    end

    resources :official_mails, path: 'mails', except: 'index' do
      member do
        get 'assign_state'
        get 'pdf'
      end

      resources :conformations, only: [:create]

      # Приложенные документы
      resources :attached_documents, only: [:index, :create, :destroy] do
        post 'confirm', on: :collection
      end
    end

    resources :orders, except: 'index' do
      member do
        get 'assign_state'
        get 'reject'
        post 'reject', to: :create_reject
        get 'pdf'
      end

      resources :conformations, only: [:create]

      # Приложенные документы
      resources :attached_documents, only: [:index, :create, :destroy] do
        post 'confirm', on: :collection
      end
    end

    resources :reports, except: 'index' do
      member do
        get 'assign_state'
        get 'pdf'
      end

      resources :conformations, only: [:create]

      # Приложенные документы
      resources :attached_documents, only: [:index, :create, :destroy] do
        post 'confirm', on: :collection
      end
    end

    resources :task_lists, only: [:update]
  end

  # Модуль ПРОПУСКА
  resources :permits, except: [:index] do
    get 'by_type/:type' => 'permits#index', on: :collection, as: :scope
    get 'status_change/:status' => 'permits#status_change', on: :member, as: :status_change
  end


  # Модуль ЗАДАЧИ
  get '/tasks' => 'tasks#index', as: :tasks



  # особая область только тестовых роутингов
  # эти роутинги доступны только для разработчиков и тестировщиков
  # на продакшене эти роутинги не должны быть доступны
  # unless Rails.env.demo? || Rails.env.production?
    get 'library' => 'library#library'
  # end

end

app/models/concerns/documents/accountable.rb
module Documents::Accountable
  extend ActiveSupport::Concern

  included do
    has_one :document, as: :accountable, dependent: :destroy

    accepts_nested_attributes_for :document

    validates_presence_of :document

    # default_scope -> {includes(:document)}

    scope :with_state, ->(state) { where('documents.state' => state) }

    scope :from_org, ->(o_id) { where('documents.sender_organization_id' => o_id) }

    scope :to_org, ->(o_id) { where('documents.recipient_organization_id' => o_id) }

    scope :from_or_to, lambda { |o_id|
      where do
        (document.sender_organization_id.eq(o_id) |
            (document.recipient_organization_id.eq(o_id) & document.state.in(%w(sent accepted rejected))))
      end
    }

    scope :approved, -> { where { document.approved_at.not_eq(nil) } }
  end

  def method_missing(method, *args)
    self.document ||= Documents::Document.new
    return document.send(method, *args) if document.respond_to?(method)
    super
  end
end

app/models/documents/accounter.rb
module Documents
  class Accounter
    def self.sign(accountable)
      document = accountable.document
      serial_number = accountable.document.try(:sn)
      document.update_column(:approved_at, Time.now)
      document.update_column(:serial_number, serial_number)
    end
  end
end

app/models/documents/conformation.rb
# == Schema Information
#
# Table name: conformations
#
#  id          :uuid             not null, primary key
#  document_id :uuid
#  user_id     :uuid
#  conformed   :boolean
#  comment     :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#
# Indexes
#
#  index_conformations_on_document_id_and_user_id  (document_id,user_id) UNIQUE
#

class Documents::Conformation < ActiveRecord::Base
  validates :comment, presence: {message: 'Коментарий обязателен при отказе согласования.'}, if: lambda {conformed == false}
  validates :document_id, presence: true
  validates :user_id, presence: true

  belongs_to :document
  belongs_to :user
end

app/models/documents/document_attached_file.rb
# == Schema Information
#
# Table name: document_attached_files
#
#  id                      :uuid             not null, primary key
#  attachment_file_name    :string(255)
#  attachment_content_type :string(255)
#  attachment_file_size    :integer
#  attachment_updated_at   :datetime
#  document_id             :uuid
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class Documents::DocumentAttachedFile < ActiveRecord::Base
  belongs_to :document

  # TODO: it causes an error if the file does not image-type
  #has_attached_file :attachment, :styles => { :pdf_thumbnail => ["171x264#", :png] }

  has_attached_file :attachment
  do_not_validate_attachment_file_type :attachment
end

app/models/documents/important.rb
module Documents
  class Important
    def initialize(current_user)
      @user = current_user
    end

    def count
      @count = incoming.count
    end

    # Accepts :orders, :mails, :reports in
    # symbols or strings
    def count_by_type(type = nil)
      type = type.to_s
      case type
      when 'orders' then order_count
      when 'mails' then mail_count
      when 'reports' then report_count
      else
        count
      end
    end

    def mail_count
      @mail_count ||=
          incoming.mails.count
    end

    def order_count
      @order_count ||=
          incoming.orders.count
    end

    def report_count
      @report_count ||=
          incoming.reports.count
    end

    def incoming
      Documents::Document.all
        # TODO: scoped?
        #inbox_ids = Document.inbox(@user.organization).unread_by(@user).map(&:id)
        #Document.includes(:notifications).where("notifications.user_id = ? OR documents.id IN (?)", @user.id, inbox_ids)
    end
  end
end

app/models/documents/official_mail.rb
# == Schema Information
#
# Table name: official_mails
#
#  id         :uuid             not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module Documents
  class OfficialMail < ActiveRecord::Base
    include Accountable

    has_and_belongs_to_many :recipients,
                            class_name: 'Organization'

    validate :recipients_present?

    amoeba do
      clone :document
    end
    
    private

    def recipients_present?
      msg = I18n.t('activerecord.errors.models.documents.official_mail.attributes.recipient_ids.blank')
      unless recipient_organization || recipients.any?
        errors.add('recipient_ids', msg)
      end
    end
  end
end

app/models/documents/report.rb
# coding: utf-8
# == Schema Information
#
# Table name: reports
#
#  id         :uuid             not null, primary key
#  order_id   :uuid             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_reports_on_order_id  (order_id)
#

module Documents
  class Report < ActiveRecord::Base
    include Accountable
    belongs_to :order

    validates_presence_of :order_id
  end
end

app/controllers/concerns/documents/accountable_controller.rb
module Documents::AccountableController
  extend ActiveSupport::Concern

  included do
    layout 'documents/base'

    # Проверяем права ползователя на чтение соответствующего документа
    before_filter :authorize_to_read_document, only: :show
    # Проверяем права ползователя на редактирование соответствующего документа
    before_filter :authorize_to_update_document, only: [:edit, :update]

    rescue_from CanCan::AccessDenied do |exception|
      redirect_to documents_path, :flash => { :error => exception.message }
    end

    before_filter :clear_notifications, only: :show
    actions :all, except: [:index]
  end

  # TODO: @prikha remove if-else mess.
  def create
    create! do |success, failure|
      success.html do
        # Посылаем уведомления исполнителю, контрольному лицу, всем согласующим
        # (если кто-то из вышеперечисленных - текущий юзер (создатель), ему не посылаем)
        resource.notify_interesants exclude: current_user

        # Обычное сохранение - нажата кнопка перевода статуса ("Подготовить" или "В черновик")
        if params.has_key?(:transition_to)
          
          resource.state = (params[:transition_to] == 'prepared') ? 'prepared' : 'draft'
          resource.save
          redirect_to documents_documents_path

        # Нажата кнопка "Прикрепить документы". В этом случае сохраняем документ как черновик и переадресуем на другую страницу
        elsif params.has_key?(:attached_documents)
          resource.state = (params[:transition_to] == 'prepared') ? 'prepared' : 'draft'
          resource.save
          redirect_to polymorphic_path([resource, :attached_documents])
        end
      end
      failure.html { render action: 'new' }
    end
  end

  def edit
    resource.document.update_attribute(:creator, current_user)
    resource.document.clear_conformations
  end

  def update
    if params.has_key?(:transition_to)
      resource.state = (params[:transition_to] == 'prepared') ? 'prepared' : 'draft'
    end
    
    resource.document.clear_conformations

    update! do |success, failure|
      success.html do
        # Посылаем уведомления всем, кроме создателя и текущего пользователя
        resource.clear_notifications
        resource.reload.notify_interesants exclude: current_user
        
        redirect_to documents_path
      end

      failure.html { render action: 'edit' }
    end
  end

  # рендерим pdf документ с помощью pdfjs
  def pdf
    render 'documents/application/pdf', layout: false
  end

  private

  def default_metadata
    { user_id: current_user.id }
  end

  def clear_notifications
    resource.clear_notifications for: current_user
  end

  def authorize_to_read_document
    true
    # authorize! :read, resource.document, message: I18n.t('unauthorized.read.document')
  end

  def authorize_to_update_document
    true
    # authorize! :update, resource.document, message: I18n.t('unauthorized.read.document')
  end
end

app/controllers/documents/attached_documents_controller.rb
# coding: utf-8
class Documents::AttachedDocumentsController < BaseController
  layout 'documents/simple'

  def index
    document = get_document(params)
    @accountable = document.accountable
    attacher = Documents::DocumentAttacher.new(document, session, current_user)

    # Если пользователь зашел в первый раз или после ухода со страницы без подтверждения,
    #   - удаляем все временные документы (которые пользователь мог добавить в прошлый раз, но не сохранить)
    #   - сбрасываем все метки на удаление (которые пользователь мог поставить в прошлый раз, но не сохранить)
    attacher.clear unless params[:continue]

    # Список текущих (предварительно прикрепленных) документов
    @attached_documents = attacher.attached_documents

    # Список документов, которые в данный момент можно прикрепить
    attachable_documents = attacher.attachable_documents.page(params[:page]).per(10)

    list_decorator = Documents::ListDecorator
    each_decorator = Documents::ListShowDecorator
    @attachable_documents = list_decorator.decorate attachable_documents, with: each_decorator
  end

  # На самом деле мы ничего не создаем в БД, создание будет при подтверждении (action confirm)
  def create
    document = get_document(params)    
    attacher = Documents::DocumentAttacher.new(document, session, current_user)
    attacher.attach(params[:attached_id])

    # Редирект на index с меткой продолжения операции
    redirect_to_index document
  # rescue
    # flash[:error] = 'Не удалось прикрепить документ.'
    # redirect_to_index document
  end

  # На самом деле здесь ничего не удаляется, удаление будет происходить при подтверждении (action confirm)
  def destroy
    document = get_document(params)
    attacher = Documents::DocumentAttacher.new(document, session, current_user)

    attacher.detach params[:id]

    redirect_to_index document
  # rescue
  #   flash[:error] = 'Не удалось открепить документ.'
  #   redirect_to_index document  
  end

  def confirm
    document = get_document(params)
    attacher = Documents::DocumentAttacher.new(document, session, current_user)

    attacher.confirm    

    redirect_to polymorphic_path([:edit, document.accountable])
  rescue
    flash[:error] = 'Некоторые документы не удалось прикрепить или открепить.'
    redirect_to_index document  
  end

private
  # options[:continue]. Boolean. Pass continue GET param? Default: true
  def redirect_to_index (document, options = {})
    options[:continue] ||= true

    redirect_to polymorphic_path([document.accountable, :attached_documents], params: {continue: options[:continue]})  
  end

  def get_document(params)
    if (id = params[:official_mail_id])
      Documents::OfficialMail.find(id).document
    elsif (id = params[:report_id])
      Documents::Report.find(id).document
    elsif (id = params[:order_id])
      Documents::Order.find(id).document
    end
  end
end

app/controllers/documents/conformations_controller.rb
class Documents::ConformationsController < Documents::ResourceController

  def create
    doc = get_document(params)
    if conformation_params
      if conformed?
        @conform = current_user.conform doc, comment: conformation_params[:comment]
      else
        @conform = current_user.deny doc, conformation_params[:comment]
      end
      # TODO-vladimir: как-то не красиво выглядит эта связь, надо уже и в контроллерах писать «релоад» согласований
      @conformations = doc.conformations.reload

      # Если все согласовали положительно
      if @conformations.where(conformed: true).count == doc.conformers.count
        begin
          # NotificationMailer.document_conformed(doc).deliver!
        rescue
          # Nothing
        end
        doc.reload.notify_interesants only: :approver, exclude: current_user
      end

      respond_to { |format| format.js { render layout: false } }
    end
  rescue Exception => e
    render json: e.message

  # данная строчка добавлена для тестирования работы фронтенда при многократном отсылании голосований
  #respond_to { |format| format.js { render layout: false } }
  end

  private

  def conformed?
    (conformation_params[:conformed] == 'true')? true : false
  end

  def conformation_params
    params.require(:documents_conformation).permit(:conformed, :comment)
  end

  def get_document(params)
    if (id = params[:official_mail_id])
      Documents::OfficialMail.find(id).document
    elsif (id = params[:report_id])
      Documents::Report.find(id).document
    elsif (id = params[:order_id])
      Documents::Order.find(id).document
    end
  end

end

app/controllers/documents/document_attached_files_controller.rb
class Documents::DocumentAttachedFilesController < ApplicationController
  def destroy
    @attachment = DocumentAttachedFile.find(params[:id])
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/views/documents/documents/_condition_fields.html.slim
.form-group
  = f.attribute_fields do |a|
    = a.attribute_select
  = f.predicate_select only: [:cont]
  = f.value_fields do |v|
    = v.text_field :value
  = link_to "remove", '#', class: "remove_fields"

app/views/documents/documents/_filter.html.slim
#myModal.modal.fade.js-document-filter-modal aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      = search_form_for @search, url: documents_documents_path, \
                        html: { class: 'form-horizontal js-filter-form', data: {url: search_documents_documents_path } } \
                        do |f|
        .modal-header
          h4#myModalLabel.modal-title Расширенный поиск по документам
        .modal-body
          .js-filter-container
            .nav.nav-inline.b-offset-sm
              - %w{Documents::Report Documents::Order Documents::OfficialMail}.each do |name|
                li.checkbox
                  = label_tag "q_accountable_type_in_#{name.downcase.gsub('::', '')}", class: 'control-label' do
                    = f.check_box :accountable_type_in, { multiple: true, checked: true }, name
                    span = t("activerecord.attributes.documents/document.accountable_types.#{name.downcase.gsub('::','_')}")

            = link_to '#', class: 'btn btn-big btn-mega-primary js-filter-add-row-btn' do
              span.fa.fa-plus-circle
              span добавить параметр фильтрации


        .hidden
          / целая дефолтная строка
          .js-filter-option-row-source
            .js-filter-row
              .form-group
                .col-sm-3
                  = select_tag :filter_attribute, options_for_select(document_filter_options), class: 'js-chosen js-filter-attribute'
                .col-sm-7.js-filter-query
                  .form-group
                    .col-sm-5 = select_tag :option_types, options_for_select(document_filter_string_query_conditions), class: 'js-chosen'
                    .col-sm-7 = f.text_field :title_cont, autocomplete: 'off', class: 'form-control', data: { name: 'title' }
                .col-sm-2
                  = link_to '#', class: 'btn link-danger js-filter-row-remove-btn' do
                    span.fa.fa-minus-circle
                    span убрать

          / отдельные свойства поиска
          .js-filter-row-query-source data-type='title'
            .form-group
              .col-sm-5 = select_tag :option_types, options_for_select(document_filter_string_query_conditions), class: 'js-chosen'
              .col-sm-7 = f.text_field :title_cont, autocomplete: 'off', data: { name: 'title' }, class: 'form-control'

          .js-filter-row-query-source data-type='sender'
            .form-group
              /.col-sm-12 = f.text_field :sender_organization_id_eq, autocomplete: 'off', class: 'form-control', data: { name: 'sender_organization_id' }
              .col-sm-4.control-label содержит
              .col-sm-8 = f.text_field :sender_organization_short_title_cont, autocomplete: 'off', class: 'form-control', data: { name: 'sender_organization_id' }

          .js-filter-row-query-source data-type='recipient'
            .form-group
              .col-sm-4.control-label содержит
              .col-sm-8 = f.text_field :recipient_organization_short_title_cont, autocomplete: 'off', class: 'form-control', data: { name: 'recipient_organization_id' }

          .js-filter-row-query-source data-type='created_at'
            .form-group
              .col-sm-1.control-label с
              .col-sm-5
                .input-group
                  span.input-group-icon
                    i.fa.fa-calendar
                  = f.text_field :created_at_gteq, autocomplete: 'off', class: 'form-control js-datepicker'
              .col-sm-1.control-label до
              .col-sm-5
                .input-group
                  span.input-group-icon
                    i.fa.fa-calendar
                  = f.text_field :created_at_lteq, autocomplete: 'off', class: 'form-control js-datepicker'

          .js-filter-row-query-source data-type='approved_at'
            .form-group
              .col-sm-1.control-label с
              .col-sm-5
                .input-group
                  span.input-group-icon
                    i.fa.fa-calendar
                  = f.text_field :approved_at_gteq, autocomplete: 'off', class: 'form-control js-datepicker'
              .col-sm-1.control-label до
              .col-sm-5
                .input-group
                  span.input-group-icon
                    i.fa.fa-calendar
                  = f.text_field :approved_at_lteq, autocomplete: 'off', class: 'form-control js-datepicker'




        .modal-footer
          .row
            .col-sm-6
              .js-filter-result-count.text-left
            .col-sm-6
              = f.submit 'найти', class: 'btn btn-primary'
              = link_to 'отмена', '#', class: 'btn link-muted', data: { dismiss: 'modal' }

app/views/documents/documents/_history.html.slim
._doc-state__header
  .h4.__left
    span.fa.fa-clock-o
    span история изменений

  = link_to '#', class: 'btn btn-invert btn-sm js-document-state-back-link' do
    span.fa.fa-arrow-left
    span Назад

._doc-state__actions
  - collection.each do |transition|
    .h6
      / TODO-justvitalius: refactor to decorator
      /= t("activerecord.attributes.document.states.order.#{transition.to_state}")
      = @document.humanize_state transition.to_state
      = " — "
      = DateFormatter.new(transition.created_at, :full)

app/views/documents/documents/_quick_search_for.html.slim
= form_tag collection_path, class: 'navbar-form navbar-left', method: 'get' do

  = hidden_field_tag 'with_type', params[:with_type] if params[:with_type]
  = hidden_field_tag 'with_state', params[:with_state] if params[:with_state]

  = content_tag(:div, class: 'input-group') do
    = text_field_tag :quick, params[:quick], class: 'form-control js-input-with-icon', placeholder: 'поиск по документам'
    = content_tag(:span, nil, class: 'input-group-icon search')

app/views/documents/documents/_table.html.slim
.row
  table.table.js-row-clickable.m-table-replacement.js-table-filter
    thead
      = search_form_for @search,  url: documents_documents_path(params[:q]), html: { class: 'form-horizontal', data: { url: search_documents_documents_path }, multiple: true } do |f|

        = hidden_field_tag :with_state, params[:with_state]
        = hidden_field_tag :with_type, params[:with_type]

      tr
        / th = check_box_tag :selected, nil, false, class: 'js-select-all-in-table', data:{ target: 'document' }
        th.col-words-9
          span = t('documents.table.list_attrs.number_and_date')
          .pull-right = resource_sortable_icon 'approved_at', class: 'label label-sm label-icon'

        th.col-words-15
          = table_filter_caption t('documents.table.list_attrs.sender_organization'), @search, :sender_organization_id_in, 'document-table-filter-sender-organization'
          .pull-right = resource_sortable_icon   'organizations.short_title', class: 'label label-sm label-icon'


        th.col-words-17
          = table_filter_caption t('documents.table.list_attrs.recipient_organization'), @search, :recipient_organization_id_in, 'document-table-filter-recipient-organization'
          .pull-right = resource_sortable_icon 'recipient_organizations_documents.short_title', class: 'label label-sm label-icon'


        th
          = table_filter_caption t('documents.table.list_attrs.title'), @search, :title_cont, 'document-table-filter-title'
          .pull-right = resource_sortable_icon 'title', class: 'label label-sm label-icon'

        th.col-words-5 = table_filter_caption t('documents.table.list_attrs.type'), @search, :accountable_type_cont_any, 'document-table-filter-document-type'
        th = table_filter_caption t('documents.table.list_attrs.conformation'), @search, [:conformers_id_not_null, :conformations_conformed_in], 'document-table-filter-conformations'
        /th
          .label.label-sm = t('documents.table.list_attrs.conformation')
        th = table_filter_caption t('documents.table.list_attrs.status'), @search, :state_cont_any, 'document-table-filter-state'

      / строка со статусом фильтра показывается, только если применены настройки фильтра
      - if @search.respond_to?(:conditions) && @search.try(:conditions).any?
        tr
          th.js-table-filter-status-bar colspan=8
            .btn-block.text-center
              h3.text-heading-alt
                span.fa.fa-filter
                span Фильтр включен
              = link_to 'изменить', '#', class: 'link link-muted js-table-filter-status-bar-change-btn'
              = link_to 'сбросить', '#', class: 'link link-muted js-table-filter-status-bar-clear-btn'

      / строки с самими элементами форм фильтра
      tr = table_filter_chosen @search, 'sender_organization', :sender_organization_id_in, document_filter_organizations, 'document-table-filter-sender-organization'
      tr = table_filter_chosen @search, 'recipient_organization', :recipient_organization_id_in, document_filter_organizations, 'document-table-filter-recipient-organization'
      tr = table_filter_text @search, 'title', :title_cont, 'document-table-filter-title'
      tr = table_filter_chosen @search, 'document_type', :accountable_type_cont_any, document_filter_document_types, 'document-table-filter-document-type'
      tr
        th.js-table-filter-form.form-horizontal data-target='document-table-filter-conformations' colspan=8
          = search_form_for @search,  url: documents_documents_path, html: { class: 'form-horizontal', data: { url: search_documents_documents_path }, multiple: true } \
                                            do |f|
            h3 Согласованность
            .form-group.b-offset-sm
              = f.label :conformations_conformed_in, class: 'checkbox-inline' do
                = check_box_tag 'q[conformations_conformed_in][]', true, ([*params[:q][:conformations_conformed_in]].include?('true') if params.has_key?(:q))
                span Согласованы

              = f.label :conformations_conformed_in, class: 'checkbox-inline' do
                = check_box_tag 'q[conformations_conformed_in][]', false, ([*params[:q][:conformations_conformed_in]].include?('false') if params.has_key?(:q))
                span Отклонены

              = f.label :conformers_id_not_null, class: 'checkbox-inline' do
                = check_box_tag 'q[conformers_id_not_null]', true, ([*params[:q][:conformers_id_not_null]].include?('true') if params.has_key?(:q))
                span Ожидают согласования

            = table_filter_buttons(f)

      tr = table_filter_chosen @search, 'state', :state_cont_any, document_filter_states, 'document-table-filter-state'


    tbody
      - if  collection.empty?
        tr
          td colspan=7
            .text-center.text-important по заданным параметрам фильтрации документов нет
      - else
        - attrs = [:number_and_date, :sender_link, :recipient_link, :title, :type_name, :conformation_icon]
        - collection.each do |resource|
          / simple row with short information
          tr class=documents_important.row_class(resource)
            - attrs.each do |attr|
              td.js-info = resource.send(attr.to_sym)

            td[ colspan=attrs.count class='js-more-info']
              .row
                span.h2.col-sm-11.col-offset-1 = resource.title_link
              .row
                .col-sm-4.col-offset-1
                  div= resource.type_name
                  div= resource.link_to_pdf class: 'table-img-md'
                  /div= pdf_to_png(resource,190,270)
                .col-sm-7
                  .row = resource.sender_to_recipient_links
                  .row = resource.number_and_date_with_label
                  .row = resource.executor_link_with_label
                  .row = resource.recipient_link_with_label
                  .row = resource.sender_link_with_label
                  .row = resource.attachments_count_with_label
            td.js-visible
              = render 'documents/application/document_state_popover', document: resource

app/views/documents/documents/history.js.erb
$('.js-document-state-popover').html("<%= j render 'history', collection: @transitions %>")

app/views/documents/documents/index.html.slim
= content_for :page_header do
  h1 Список документов

= content_for :page_header_search do
  = render 'quick_search_for'

= render 'filter'
ul.nav.nav-inline.btn-block
  li.dropdown
    = link_to '#', class: 'dropdown-toggle btn btn-primary', data:{ toggle: 'dropdown' } do
      span Создать
      span.caret
    ul.dropdown-menu
      li= link_to 'Письмо', new_polymorphic_path(Documents::OfficialMail)
      li= link_to 'Предписание', new_polymorphic_path(Documents::Order)
      li= link_to 'Акт', new_polymorphic_path(Documents::Report)

  /  ниспдаюащий список с действиями над группой документов
  /li.dropdown
  /  = link_to '#', class: 'dropdown-toggle btn btn-default', data:{ toggle: 'dropdown' } do
  /    span Действия
  /    span.caret
  /  ul.dropdown-menu.js-documents-actions-list
  /    li выберите документы
  li
    = link_to '#', class: 'btn btn-default', data: { toggle: 'modal', target: '.js-document-filter-modal' } do
      span.fa.fa-filter
      span Фильтр
  li
    = link_to request.url, class: 'btn btn-default' do
      span.fa.fa-refresh
  li = link_to 'сбросить фильтрацию', documents_path, class: 'btn btn-link-muted'

= render 'table'
= paginate collection

app/views/documents/documents/search.js.erb
$('.js-filter-result-count').text("Всего найдено: <%= @documents.count %>");